package:
    name: libstatiskit_pgm
    version: "1.0.0"

source:
    path: ../../..

build:
    number: 0
    
about:
    home: http://statiskit-pgm.readthedocs.io/
    license: Apache License 2.0

requirements:
    build:
        - libtoolchain
        - libboost
        - libstatiskit_core
        - libstatiskit_glm
    run:
        - libruntime
        - libboost
        - libstatiskit_core
        - libstatiskit_glm
