#include "_pgm.h"



namespace autowig
{

    void method_decorator_85394b1fafed516e89070d1bc9269675(class ::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > > & instance, ::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::size_type  param_in_0, const ::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::reference  param_out) { instance.at(param_in_0) = param_out; }
    void method_decorator_f467a95708b15c238cf4a76da246c725(class ::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > > & instance, const ::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::reference  param_out) { instance.front() = param_out; }
    void method_decorator_f1265057fc1f5cc6a25f730a68f0e2f9(class ::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > > & instance, const ::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::reference  param_out) { instance.back() = param_out; }
}

#if defined(_MSC_VER)
    #if (_MSC_VER == 1900)
namespace boost
{
    template <> class ::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > > const volatile * get_pointer<class ::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > > const volatile >(class ::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > > const volatile *c) { return c; }
}
    #endif
#endif



void wrapper_58063898f8e0510f98fc387ce09f4ed6()
{

    std::string name_a5e4e9231d6351ccb0e06756b389f0af = boost::python::extract< std::string >(boost::python::scope().attr("__name__") + ".std");
    boost::python::object module_a5e4e9231d6351ccb0e06756b389f0af(boost::python::handle<  >(boost::python::borrowed(PyImport_AddModule(name_a5e4e9231d6351ccb0e06756b389f0af.c_str()))));
    boost::python::scope().attr("std") = module_a5e4e9231d6351ccb0e06756b389f0af;
    boost::python::scope scope_a5e4e9231d6351ccb0e06756b389f0af = module_a5e4e9231d6351ccb0e06756b389f0af;
    void  (::std::vector< ::std::set< unsigned long int, ::std::less< unsigned long int >, ::std::allocator< unsigned long int > >, ::std::allocator< ::std::set< unsigned long int, ::std::less< unsigned long int >, ::std::allocator< unsigned long int > > > >::*method_pointer_fff6d59f04d15ef68798e881614bc4df)(::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::size_type , ::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::value_type const &) = &::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::assign;
    ::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::size_type  (::std::vector< ::std::set< unsigned long int, ::std::less< unsigned long int >, ::std::allocator< unsigned long int > >, ::std::allocator< ::std::set< unsigned long int, ::std::less< unsigned long int >, ::std::allocator< unsigned long int > > > >::*method_pointer_0c069110a76b55cdb7c583defdb03d27)() const = &::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::size;
    ::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::size_type  (::std::vector< ::std::set< unsigned long int, ::std::less< unsigned long int >, ::std::allocator< unsigned long int > >, ::std::allocator< ::std::set< unsigned long int, ::std::less< unsigned long int >, ::std::allocator< unsigned long int > > > >::*method_pointer_9acd0b6831f052b88b0773ce0a639c5a)() const = &::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::max_size;
    ::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::size_type  (::std::vector< ::std::set< unsigned long int, ::std::less< unsigned long int >, ::std::allocator< unsigned long int > >, ::std::allocator< ::std::set< unsigned long int, ::std::less< unsigned long int >, ::std::allocator< unsigned long int > > > >::*method_pointer_56a64e7d9edf5a4bb6794d08110fc156)() const = &::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::capacity;
    bool  (::std::vector< ::std::set< unsigned long int, ::std::less< unsigned long int >, ::std::allocator< unsigned long int > >, ::std::allocator< ::std::set< unsigned long int, ::std::less< unsigned long int >, ::std::allocator< unsigned long int > > > >::*method_pointer_5d322bc16343506683e074511f65d2d4)() const = &::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::empty;
    void  (::std::vector< ::std::set< unsigned long int, ::std::less< unsigned long int >, ::std::allocator< unsigned long int > >, ::std::allocator< ::std::set< unsigned long int, ::std::less< unsigned long int >, ::std::allocator< unsigned long int > > > >::*method_pointer_c42a132a97c5584bbe44025ff8eb1e55)(::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::size_type ) = &::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::reserve;
    ::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::reference  (::std::vector< ::std::set< unsigned long int, ::std::less< unsigned long int >, ::std::allocator< unsigned long int > >, ::std::allocator< ::std::set< unsigned long int, ::std::less< unsigned long int >, ::std::allocator< unsigned long int > > > >::*method_pointer_85394b1fafed516e89070d1bc9269675)(::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::size_type ) = &::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::at;
    ::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::const_reference  (::std::vector< ::std::set< unsigned long int, ::std::less< unsigned long int >, ::std::allocator< unsigned long int > >, ::std::allocator< ::std::set< unsigned long int, ::std::less< unsigned long int >, ::std::allocator< unsigned long int > > > >::*method_pointer_c87265f3880e5d018a2ec9082289d9dc)(::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::size_type ) const = &::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::at;
    ::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::reference  (::std::vector< ::std::set< unsigned long int, ::std::less< unsigned long int >, ::std::allocator< unsigned long int > >, ::std::allocator< ::std::set< unsigned long int, ::std::less< unsigned long int >, ::std::allocator< unsigned long int > > > >::*method_pointer_f467a95708b15c238cf4a76da246c725)() = &::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::front;
    ::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::const_reference  (::std::vector< ::std::set< unsigned long int, ::std::less< unsigned long int >, ::std::allocator< unsigned long int > >, ::std::allocator< ::std::set< unsigned long int, ::std::less< unsigned long int >, ::std::allocator< unsigned long int > > > >::*method_pointer_3de7d0ad77db5a5c8658823f95bc0c04)() const = &::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::front;
    ::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::reference  (::std::vector< ::std::set< unsigned long int, ::std::less< unsigned long int >, ::std::allocator< unsigned long int > >, ::std::allocator< ::std::set< unsigned long int, ::std::less< unsigned long int >, ::std::allocator< unsigned long int > > > >::*method_pointer_f1265057fc1f5cc6a25f730a68f0e2f9)() = &::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::back;
    ::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::const_reference  (::std::vector< ::std::set< unsigned long int, ::std::less< unsigned long int >, ::std::allocator< unsigned long int > >, ::std::allocator< ::std::set< unsigned long int, ::std::less< unsigned long int >, ::std::allocator< unsigned long int > > > >::*method_pointer_357c9c5a670d5133964653e953830ac8)() const = &::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::back;
    class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > * (::std::vector< ::std::set< unsigned long int, ::std::less< unsigned long int >, ::std::allocator< unsigned long int > >, ::std::allocator< ::std::set< unsigned long int, ::std::less< unsigned long int >, ::std::allocator< unsigned long int > > > >::*method_pointer_daa648f3f1a9550f8530482a007f02a6)() = &::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::data;
    class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > const * (::std::vector< ::std::set< unsigned long int, ::std::less< unsigned long int >, ::std::allocator< unsigned long int > >, ::std::allocator< ::std::set< unsigned long int, ::std::less< unsigned long int >, ::std::allocator< unsigned long int > > > >::*method_pointer_ae3ea7e1c51450e3af993bbe12789bd9)() const = &::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::data;
    void  (::std::vector< ::std::set< unsigned long int, ::std::less< unsigned long int >, ::std::allocator< unsigned long int > >, ::std::allocator< ::std::set< unsigned long int, ::std::less< unsigned long int >, ::std::allocator< unsigned long int > > > >::*method_pointer_df78412ee33856ae90d00e285646b75b)(::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::value_type const &) = &::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::push_back;
    void  (::std::vector< ::std::set< unsigned long int, ::std::less< unsigned long int >, ::std::allocator< unsigned long int > >, ::std::allocator< ::std::set< unsigned long int, ::std::less< unsigned long int >, ::std::allocator< unsigned long int > > > >::*method_pointer_144b2aeb30b15241a956ca86e5c1c987)() = &::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::pop_back;
    void  (::std::vector< ::std::set< unsigned long int, ::std::less< unsigned long int >, ::std::allocator< unsigned long int > >, ::std::allocator< ::std::set< unsigned long int, ::std::less< unsigned long int >, ::std::allocator< unsigned long int > > > >::*method_pointer_206a83fa39f65e5ab2de67ad861cec0d)(class ::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > > &) = &::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::swap;
    void  (::std::vector< ::std::set< unsigned long int, ::std::less< unsigned long int >, ::std::allocator< unsigned long int > >, ::std::allocator< ::std::set< unsigned long int, ::std::less< unsigned long int >, ::std::allocator< unsigned long int > > > >::*method_pointer_a16d94fe56615670b0412f77c27b4245)() = &::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >::clear;
    boost::python::class_< class ::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >, autowig::Held< class ::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > > >::Type > class_58063898f8e0510f98fc387ce09f4ed6("_Vector_58063898f8e0510f98fc387ce09f4ed6", "", boost::python::no_init);
    class_58063898f8e0510f98fc387ce09f4ed6.def(boost::python::init<  >(""));
    class_58063898f8e0510f98fc387ce09f4ed6.def(boost::python::init< class ::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > > const & >(""));
    class_58063898f8e0510f98fc387ce09f4ed6.def("assign", method_pointer_fff6d59f04d15ef68798e881614bc4df, "");
    class_58063898f8e0510f98fc387ce09f4ed6.def("__len__", method_pointer_0c069110a76b55cdb7c583defdb03d27, "");
    class_58063898f8e0510f98fc387ce09f4ed6.def("max_size", method_pointer_9acd0b6831f052b88b0773ce0a639c5a, "");
    class_58063898f8e0510f98fc387ce09f4ed6.def("capacity", method_pointer_56a64e7d9edf5a4bb6794d08110fc156, "");
    class_58063898f8e0510f98fc387ce09f4ed6.def("empty", method_pointer_5d322bc16343506683e074511f65d2d4, "");
    class_58063898f8e0510f98fc387ce09f4ed6.def("reserve", method_pointer_c42a132a97c5584bbe44025ff8eb1e55, "");
    class_58063898f8e0510f98fc387ce09f4ed6.def("at", method_pointer_85394b1fafed516e89070d1bc9269675, boost::python::return_internal_reference<>(), "");
    class_58063898f8e0510f98fc387ce09f4ed6.def("at", autowig::method_decorator_85394b1fafed516e89070d1bc9269675);
    class_58063898f8e0510f98fc387ce09f4ed6.def("at", method_pointer_c87265f3880e5d018a2ec9082289d9dc, boost::python::return_value_policy< boost::python::return_by_value >(), "");
    class_58063898f8e0510f98fc387ce09f4ed6.def("front", method_pointer_f467a95708b15c238cf4a76da246c725, boost::python::return_internal_reference<>(), "");
    class_58063898f8e0510f98fc387ce09f4ed6.def("front", autowig::method_decorator_f467a95708b15c238cf4a76da246c725);
    class_58063898f8e0510f98fc387ce09f4ed6.def("front", method_pointer_3de7d0ad77db5a5c8658823f95bc0c04, boost::python::return_value_policy< boost::python::return_by_value >(), "");
    class_58063898f8e0510f98fc387ce09f4ed6.def("back", method_pointer_f1265057fc1f5cc6a25f730a68f0e2f9, boost::python::return_internal_reference<>(), "");
    class_58063898f8e0510f98fc387ce09f4ed6.def("back", autowig::method_decorator_f1265057fc1f5cc6a25f730a68f0e2f9);
    class_58063898f8e0510f98fc387ce09f4ed6.def("back", method_pointer_357c9c5a670d5133964653e953830ac8, boost::python::return_value_policy< boost::python::return_by_value >(), "");
    class_58063898f8e0510f98fc387ce09f4ed6.def("data", method_pointer_daa648f3f1a9550f8530482a007f02a6, boost::python::return_value_policy< boost::python::reference_existing_object >(), "");
    class_58063898f8e0510f98fc387ce09f4ed6.def("data", method_pointer_ae3ea7e1c51450e3af993bbe12789bd9, boost::python::return_value_policy< boost::python::reference_existing_object >(), "");
    class_58063898f8e0510f98fc387ce09f4ed6.def("push_back", method_pointer_df78412ee33856ae90d00e285646b75b, "");
    class_58063898f8e0510f98fc387ce09f4ed6.def("pop_back", method_pointer_144b2aeb30b15241a956ca86e5c1c987, "");
    class_58063898f8e0510f98fc387ce09f4ed6.def("swap", method_pointer_206a83fa39f65e5ab2de67ad861cec0d, "");
    class_58063898f8e0510f98fc387ce09f4ed6.def("clear", method_pointer_a16d94fe56615670b0412f77c27b4245, "");

    struct vector_58063898f8e0510f98fc387ce09f4ed6_from_python
    {
        vector_58063898f8e0510f98fc387ce09f4ed6_from_python()
        {
            boost::python::converter::registry::push_back(
                &convertible,
                &construct,
                boost::python::type_id< class ::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > > >());
        }

        static void* convertible(PyObject* obj_ptr)
        { return obj_ptr; }

        static void construct(PyObject* obj_ptr, boost::python::converter::rvalue_from_python_stage1_data* data)
        {
            boost::python::handle<> obj_iter(PyObject_GetIter(obj_ptr));
            void* storage = ((boost::python::converter::rvalue_from_python_storage< class ::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > > >*)data)->storage.bytes;
            new (storage) class ::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >();
            data->convertible = storage;
            class ::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >& result = *((class ::std::vector< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >, class ::std::allocator< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > > > >*)storage);
            unsigned int i = 0;
            for(;; i++)
            {
                boost::python::handle<> py_elem_hdl(boost::python::allow_null(PyIter_Next(obj_iter.get())));
                if(PyErr_Occurred())
                { boost::python::throw_error_already_set(); }
                if(!py_elem_hdl.get())
                { break; }
                boost::python::object py_elem_obj(py_elem_hdl);
                result.push_back(boost::python::extract< class ::std::set< unsigned long int, struct ::std::less< unsigned long int >, class ::std::allocator< unsigned long int > >  >(py_elem_obj));
            }
        }
    };

    vector_58063898f8e0510f98fc387ce09f4ed6_from_python();
}