package:
  name: python-statiskit_pgm
  version: "1.0.0"

source:
  path: ../../..

build:
  number: 0

about:
  home: http://statiskit-pgm.readthedocs.io
  license: Apache License 2.0

requirements:
  build:
    - libtoolchain
    - python-toolchain
    - libboost
    - libstatiskit_pgm
    - python
  run:
    - libruntime
    - libboost
    - python-statiskit_core
    - python-statiskit_glm
    - libstatiskit_pgm
    - python
    - networkx

test:                                               
  requires:
    - python-toolchain
    - matplotlib
    - numpy
    - pydotplus
  imports:
    - statiskit.pgm
  source_files:                                
    - test/test_*.py
  commands:                                       
   - nosetests test -s -v -A "level <= {{ environ.get('TEST_LEVEL', 3) }} and linux" [linux]
   - nosetests test -s -v -A "level <= {{ environ.get('TEST_LEVEL', 3) }} and osx"   [osx]
   - nosetests test -s -v -A "level <= {{ environ.get('TEST_LEVEL', 3) }} and win"   [win]
