package:
  name: python-statiskit_pgm
  version: "1.0.0"

source:
  path: ../..

build:
  number: 0

about:
  home: http://statiskit-pgm.readthedocs.io
  license: CeCILL

requirements:
  build:
    - libdev
    - python-dev
    - libboost
    - libstatiskit_pgm
    - python
  run:
    - librun
    - libboost
    - python-statiskit_core
    - libstatiskit_pgm
    - python
    - networkx

test:                                               
  requires:
    - python-dev
    - matplotlib
    - numpy
  # imports:
  #   - statiskit.core
  source_files:                                
    - test/test_*.py
  commands:                                       
   - nosetests test -x -s -v -A "level <= {{ environ.get('TEST_LEVEL', 3) }} and linux" [linux]
   - nosetests test -x -s -v -A "level <= {{ environ.get('TEST_LEVEL', 3) }} and osx"   [osx]
   - nosetests test -x -s -v -A "level <= {{ environ.get('TEST_LEVEL', 3) }} and win"   [win]
